/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer_tidakpakedollar;

import restaurant_tidakpakaidollar.*;

/**
 *
 * @author Giffert
 */
public class FormReservation extends javax.swing.JFrame {

    /**
     * Creates new form FormReservation
     */
    int currentUserId;
    String currentUsername;
    FormDashboardCustomer dashboardForm;

    public FormReservation() {
        initComponents();
    }

    public FormReservation(FormDashboardCustomer parent, int userId, String username) {
        initComponents();
        this.dashboardForm = parent;
        this.currentUserId = userId;
        this.currentUsername = username;
        setLocationRelativeTo(null);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneReservationHistory = new javax.swing.JScrollPane();
        tblReservationHistory = new javax.swing.JTable();
        lblUpcomingReservation = new javax.swing.JLabel();
        lblReservationHistory = new javax.swing.JLabel();
        jScrollPaneUpcomingReservation = new javax.swing.JScrollPane();
        tblUpcomingReservation = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tblReservationHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblReservationHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Status", "Guest"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservationHistory.setRowHeight(30);
        jScrollPaneReservationHistory.setViewportView(tblReservationHistory);

        lblUpcomingReservation.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUpcomingReservation.setText("Upcoming Reservation");

        lblReservationHistory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblReservationHistory.setText("Reservation History");

        tblUpcomingReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblUpcomingReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Status", "Guest"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUpcomingReservation.setRowHeight(30);
        jScrollPaneUpcomingReservation.setViewportView(tblUpcomingReservation);

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(jScrollPaneUpcomingReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReservationHistory)
                    .addComponent(lblUpcomingReservation)
                    .addComponent(jScrollPaneReservationHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUpcomingReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneUpcomingReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblReservationHistory)
                .addGap(12, 12, 12)
                .addComponent(jScrollPaneReservationHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dashboardForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JScrollPane jScrollPaneReservationHistory;
    private javax.swing.JScrollPane jScrollPaneUpcomingReservation;
    private javax.swing.JLabel lblReservationHistory;
    private javax.swing.JLabel lblUpcomingReservation;
    private javax.swing.JTable tblReservationHistory;
    private javax.swing.JTable tblUpcomingReservation;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        javax.swing.table.DefaultTableModel upcomingModel = (javax.swing.table.DefaultTableModel) tblUpcomingReservation.getModel();
        javax.swing.table.DefaultTableModel historyModel = (javax.swing.table.DefaultTableModel) tblReservationHistory.getModel();
        upcomingModel.setRowCount(0);
        historyModel.setRowCount(0);

        try {
            dashboardForm.restaurantClient.sendMessageToServer("GET_RESERVATION");
            dashboardForm.restaurantClient.response = dashboardForm.restaurantClient.getMessageFromServer();
            String response = dashboardForm.restaurantClient.response;
            
            if (response != null && !response.isEmpty() && !response.equals("ERROR")) {
                String[] reservations = response.split("#");
                for (String res : reservations) {
                    if (res.trim().isEmpty()) {
                        continue;
                    }
                    String[] data = res.split(";");
                    if (data.length < 5) {
                        continue;
                    }

                    String datetimeStr = data[1];
                    String status = data[2];
                    String guest = data[3];
                    String username = data[4];

                    if (!username.equals(this.currentUsername)) {
                        continue;
                    }

                    String date = datetimeStr;
                    String time = "";
                    if (datetimeStr.contains(" ")) {
                        date = datetimeStr.split(" ")[0];
                        time = datetimeStr.split(" ")[1];
                        if (time.length() > 5) {
                            time = time.substring(0, 5);
                        }
                    }

                    if (status.equals("ACCEPTED") || status.equals("ONGOING")) {
                        upcomingModel.addRow(new Object[]{date, time, status, guest});
                    } else if (status.equals("FINISHED") || status.equals("CANCELED")) {
                        historyModel.addRow(new Object[]{date, time, status, guest});
                    }
                }
            }
        } catch (java.io.IOException ex) {
            System.out.println("Error loading reservation data: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Koneksi ke server bermasalah: " + ex.getMessage());
        }
    }
}