/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer_tidakpakedollar;

import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicholas
 */
public class FormOrderMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormOrderMenu
     */
    int reservationId;
    FormDashboardCustomer dashboardForm;

    String[][] allMenu;
    ArrayList<String[]> keranjang = new ArrayList<>();
    
    int selectedMenuId, selectedMenuPrice, selectedMenuStock; String selectedMenuName, selectedMenuCategory;
    public FormOrderMenu() {
        initComponents();
    }

    public FormOrderMenu(FormDashboardCustomer parent, int pReservationId) throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        this.reservationId = pReservationId;
        this.dashboardForm = parent;

        String request = "GET_MENU";
        dashboardForm.restaurantClient.sendMessageToServer(request);
        dashboardForm.restaurantClient.response = dashboardForm.restaurantClient.getMessageFromServer();
        String menus = dashboardForm.restaurantClient.response;
        String[] menuItem = menus.split("#");
        allMenu = new String[menuItem.length][5];

        for (int i = 0; i < menuItem.length; i++) {
            String menuItemDetail[] = menuItem[i].split(";");
            for (int j = 0; j < 5; j++) {
                allMenu[i][j] = menuItemDetail[j];
            }
        }
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateOrder = new javax.swing.JLabel();
        jScrollPaneDaftarMenu = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnKode = new javax.swing.JLabel();
        lblKeranjangPesanan = new javax.swing.JLabel();
        lblDaftarMenu = new javax.swing.JLabel();
        btnJumlah = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblNamaMenu = new javax.swing.JLabel();
        btnTambahOrder = new javax.swing.JButton();
        spinnerJumlah = new javax.swing.JSpinner();
        spinnerKode = new javax.swing.JSpinner();
        txtNamaMenu = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jScrollPaneKeranjangPesanan = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        txtCariMenu = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        btnPesan = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        lblCari1 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCreateOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCreateOrder.setText("Create Order");

        tblMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Category", "Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDaftarMenu.setViewportView(tblMenu);

        btnKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKode.setText("Kode");

        lblKeranjangPesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKeranjangPesanan.setText("Keranjang Pesanan");

        lblDaftarMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDaftarMenu.setText("Daftar Menu");

        btnJumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJumlah.setText("Jumlah");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHarga.setText("Harga");

        lblNamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaMenu.setText("Nama Menu");

        btnTambahOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTambahOrder.setText("Tambah");
        btnTambahOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahOrderActionPerformed(evt);
            }
        });

        spinnerJumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spinnerKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerKode.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerKode.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerKodeStateChanged(evt);
            }
        });

        txtNamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNamaMenu.setEnabled(false);

        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHarga.setEnabled(false);

        tblKeranjang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Category", "Price", "Amount", "Subtotal", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeranjangMouseClicked(evt);
            }
        });
        jScrollPaneKeranjangPesanan.setViewportView(tblKeranjang);

        lblCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCari.setText("Cari");

        txtCariMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCariMenu.setEnabled(false);

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));

        btnPesan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnHitung.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Total: Rp.");

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        lblCari1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCari1.setText("Cari Berdasarkan");

        cmbCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Nama" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblDaftarMenu)
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCari1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCari)
                                .addGap(18, 18, 18)
                                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCariMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPaneDaftarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHitung)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesan))
                    .addComponent(jScrollPaneKeranjangPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJumlah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerJumlah))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKode)
                                .addGap(22, 22, 22)
                                .addComponent(spinnerKode)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaMenu)
                                    .addComponent(lblHarga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahOrder))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblKeranjangPesanan)
                                .addGap(148, 148, 148)))))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(lblCreateOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCreateOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari)
                            .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCari1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCari)
                            .addComponent(txtCariMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDaftarMenu)
                            .addComponent(lblKeranjangPesanan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnKode)
                                    .addComponent(spinnerKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNamaMenu)
                                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnJumlah)
                                    .addComponent(lblHarga)
                                    .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTambahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneKeranjangPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesan)
                            .addComponent(btnHitung)
                            .addComponent(lblTotal)))
                    .addComponent(jScrollPaneDaftarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            String filterBy = "", value = "";
            String request = "";
            if (cmbCari.getSelectedIndex() == 0) {
                filterBy = "category";
                value = cmbKategori.getSelectedItem().toString();
                if (value.equals("Makanan"))
                {
                    value = "FOOD";
                } else {
                    value = "DRINK";
                }
            } else if (cmbCari.getSelectedIndex() == 1) {
                filterBy = "name";
                value = txtCariMenu.getText().trim();
            }   if (value.isEmpty()) {
                request = "GET_MENU";
            } else {
                request = "GET_MENU;" + filterBy + ";" + value;
            }   
            dashboardForm.restaurantClient.sendMessageToServer(request);
            dashboardForm.restaurantClient.getMessageFromServer();
            String menus = dashboardForm.restaurantClient.response;
            if (menus == null || menus.trim().isEmpty()) {
                allMenu = new String[0][5];
            } else {
                String[] menuItem = menus.split("#");
                allMenu = new String[menuItem.length][5];
                
                for (int i = 0; i < menuItem.length; i++) {
                    String menuItemDetail[] = menuItem[i].split(";");
                    for (int j = 0; j < 5; j++) {
                        if (j < menuItemDetail.length) {
                            allMenu[i][j] = menuItemDetail[j];
                        } else {
                            allMenu[i][j] = "";
                        }
                    }
                }
            }   refreshTable();
        } catch (IOException ex) {
            Logger.getLogger(FormOrderMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int total = 0;
        for (int i = 0; i < keranjang.size(); i++){
            total += Integer.parseInt(keranjang.get(i)[5]);
        }
        lblTotal.setText("Total: Rp." + total);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnTambahOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahOrderActionPerformed
        int jumlah = (int) spinnerJumlah.getValue();
        if (jumlah > selectedMenuStock) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Stock tidak cukup.","", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        boolean sudahAda = false;
        for (int i = 0; i < keranjang.size(); i++) {
            String[] item = keranjang.get(i);
            if (Integer.parseInt(item[0]) == selectedMenuId) {
                int jumlahLama = Integer.parseInt(item[4]);
                int jumlahBaru = jumlahLama + jumlah;
                if (jumlahBaru > selectedMenuStock) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Stock tidak cukup.", "", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                item[4] = String.valueOf(jumlahBaru);
                item[5] = String.valueOf(selectedMenuPrice * jumlahBaru);
                model.setValueAt(jumlahBaru, i, 4);
                model.setValueAt(selectedMenuPrice * jumlahBaru, i, 5);
                sudahAda = true;
                break;
            }
        }
        if (!sudahAda) {
            String[] data = new String[6];
            data[0] = String.valueOf(selectedMenuId);
            data[1] = selectedMenuName;
            data[2] = selectedMenuCategory;
            data[3] = String.valueOf(selectedMenuPrice);
            data[4] = String.valueOf(jumlah);
            data[5] = String.valueOf(selectedMenuPrice * jumlah);
            keranjang.add(data);
            Object[] rowData = {
                selectedMenuId,
                selectedMenuName,
                selectedMenuCategory,
                selectedMenuPrice,
                jumlah,
                selectedMenuPrice * jumlah,
                "Delete"
            };
            model.addRow(rowData);
        }       
    }//GEN-LAST:event_btnTambahOrderActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, "Buat pesanan? Anda tidak bisa mengubah pesanan setelah konfirmasi dan pembayaran", "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            boolean sukses = true;
            for (int i = 0; i < keranjang.size(); i++) {
                try {
                    String request = "CREATE_ORDER_DETAIL;"
                            + keranjang.get(i)[0] + ";"
                            + reservationId + ";"
                            + keranjang.get(i)[4] + ";"
                            + keranjang.get(i)[5];
                    dashboardForm.restaurantClient.sendMessageToServer(request);
                    dashboardForm.restaurantClient.getMessageFromServer();
                    String response = dashboardForm.restaurantClient.response;
                    if (response.equals("CREATE_ORDER_FAILED")) {
                        sukses = false;
                        JOptionPane.showMessageDialog(this, "Gagal menambahkan item " + keranjang.get(i)[1] );
                        break;
                    }
                } catch (IOException ex) {
                    sukses = false;
                    break;
                }
            }
            if (sukses) {
                try {
                    JOptionPane.showMessageDialog(this, "Pesanan berhasil dibuat");
                    int total = 0;
                    for (int i = 0; i < keranjang.size(); i++) {
                        total += Integer.parseInt(keranjang.get(i)[5]);
                    }
                    String request = "CREATE_INVOICE;" + this.reservationId + ";" + total;
                    dashboardForm.restaurantClient.sendMessageToServer(request);
                    dashboardForm.restaurantClient.response = dashboardForm.restaurantClient.getMessageFromServer();
                    String response = dashboardForm.restaurantClient.response;
                    JOptionPane.showMessageDialog(this, response);
                    
                    if (response.equals("INVOICE_SUCCESS")) {
                        JOptionPane.showMessageDialog(this, "Invoice berhasil dibuat");
                        //paggil form invoice
                    } else if (response.equals("INVOICE_FAILED")) {
                        JOptionPane.showMessageDialog(this, "Invoice gagal dibuat");
                    }
                    
                    
                } catch (IOException ex) {
                    Logger.getLogger(FormOrderMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }            
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        if (cmbCari.getSelectedIndex() == 0) {
            cmbKategori.setEnabled(true);
            txtCariMenu.setEnabled(false);
        } else if (cmbCari.getSelectedIndex() == 1) {
            cmbKategori.setEnabled(false);
            txtCariMenu.setEnabled(true);
        }
    }//GEN-LAST:event_cmbCariActionPerformed

    private void spinnerKodeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerKodeStateChanged
        selectedMenuId = (int) spinnerKode.getValue();
        boolean found = false;
        for (int i = 0; i < allMenu.length; i++) {
            if (selectedMenuId == Integer.parseInt(allMenu[i][0])) {
                selectedMenuName = allMenu[i][1];
                selectedMenuCategory = allMenu[i][2];
                selectedMenuPrice = Integer.parseInt(allMenu[i][3]); 
                selectedMenuStock = Integer.parseInt(allMenu[i][4]);                
                found = true; break;
            }
        }
        if (found) {
            txtNamaMenu.setText(selectedMenuName);
            txtHarga.setText(Integer.toString(selectedMenuPrice));
        }
        else {
            txtNamaMenu.setText("");
            txtHarga.setText("");
        }
    }//GEN-LAST:event_spinnerKodeStateChanged

    private void tblKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeranjangMouseClicked
        int row = tblKeranjang.rowAtPoint(evt.getPoint());
        int col = tblKeranjang.columnAtPoint(evt.getPoint());
        if (col == 6) { 
            int pilihan = javax.swing.JOptionPane.showConfirmDialog(
                    this,"Hapus item ini?","Konfirmasi",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );
            if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
                model.removeRow(row);
                keranjang.remove(row);
            }
        }
    }//GEN-LAST:event_tblKeranjangMouseClicked

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);

        Object[] rowData = new Object[5];

        for (int i = 0; i < allMenu.length; i++) {
            for (int j = 0; j < 5; j++) {
                rowData[j] = allMenu[i][j];
            }
            model.addRow(rowData);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOrderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOrderMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel btnJumlah;
    private javax.swing.JLabel btnKode;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnTambahOrder;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JScrollPane jScrollPaneDaftarMenu;
    private javax.swing.JScrollPane jScrollPaneKeranjangPesanan;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblCari1;
    private javax.swing.JLabel lblCreateOrder;
    private javax.swing.JLabel lblDaftarMenu;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKeranjangPesanan;
    private javax.swing.JLabel lblNamaMenu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spinnerJumlah;
    private javax.swing.JSpinner spinnerKode;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtCariMenu;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaMenu;
    // End of variables declaration//GEN-END:variables
}
