/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer_tidakpakedollar;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurant_tidakpakaidollar.*;
/**
 *
 * @author Giffert
 */
public class FormDashboardCustomer extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboardCustomer
     */
    int currentUserId;
    String currentUsername;
    
    Restaurant_tidakpakaidollar restaurantClient;
    public FormDashboardCustomer() {
        initComponents();        
    }
    
    public FormDashboardCustomer(Restaurant_tidakpakaidollar parent, int userId, String username) {
        initComponents();
        this.restaurantClient = parent;
        this.currentUserId = userId;
        this.currentUsername = username;
        lblName.setText("Welcome, " + currentUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblName = new javax.swing.JLabel();
        menuNavBar = new javax.swing.JMenuBar();
        menuReservation = new javax.swing.JMenu();
        menuItemReservationHis = new javax.swing.JMenuItem();
        menuItemNewReservation = new javax.swing.JMenuItem();
        menuProfil = new javax.swing.JMenu();
        menuItemProfil = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setText("       ");

        menuReservation.setText("Reservation");
        menuReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemReservationHis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemReservationHis.setText("Reservation History");
        menuItemReservationHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservationHisActionPerformed(evt);
            }
        });
        menuReservation.add(menuItemReservationHis);

        menuItemNewReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemNewReservation.setText("New Reservation");
        menuItemNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewReservationActionPerformed(evt);
            }
        });
        menuReservation.add(menuItemNewReservation);

        menuNavBar.add(menuReservation);

        menuProfil.setText("Profil");
        menuProfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemProfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemProfil.setText("Profil");
        menuItemProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfilActionPerformed(evt);
            }
        });
        menuProfil.add(menuItemProfil);

        menuNavBar.add(menuProfil);

        menuLogOut.setText("Logout");
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuLogOut.add(menuItemLogout);

        menuNavBar.add(menuLogOut);

        setJMenuBar(menuNavBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblName)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblName)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure want to logout?",
                "Logout Confirmation",JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                restaurantClient.sendMessageToServer("LOGOUT");
                restaurantClient.stopThread();
                this.dispose();
                Restaurant_tidakpakaidollar newApp = new Restaurant_tidakpakaidollar();
                FormLogin login = new FormLogin(newApp);
                login.setVisible(true);
                
            } catch (IOException ex) {
                Logger.getLogger(FormDashboardCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuItemProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfilActionPerformed
        try {
            FormProfil profilForm = new FormProfil(restaurantClient, currentUserId, currentUsername);
            profilForm.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(FormDashboardCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemProfilActionPerformed

    private void menuItemReservationHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservationHisActionPerformed
        FormReservation reservationHisForm = new FormReservation(restaurantClient, currentUserId, currentUsername);
        reservationHisForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemReservationHisActionPerformed

    private void menuItemNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewReservationActionPerformed
        FormNewReservation reservationForm = new FormNewReservation(restaurantClient, currentUserId, currentUsername);
        reservationForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemNewReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboardCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemNewReservation;
    private javax.swing.JMenuItem menuItemProfil;
    private javax.swing.JMenuItem menuItemReservationHis;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenuBar menuNavBar;
    private javax.swing.JMenu menuProfil;
    private javax.swing.JMenu menuReservation;
    // End of variables declaration//GEN-END:variables
    
}