/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer_tidakpakedollar;
import com.restaurant.services.*;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Giffert
 */
public class FormDashboardCustomer extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form FormDashboardCustomer
     */
    Account user;
    Socket clientSocket;
    Thread t;
    BufferedReader in;
    DataOutputStream out;
    public FormDashboardCustomer(Account a) {
        initComponents();
        user = a;
        try {
            initComponents();
            setLocationRelativeTo(null);
            clientSocket = new Socket("localhost", 6000);
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            out = new DataOutputStream(clientSocket.getOutputStream());
            
            lblName.setText("Welcome, " + user.getFullname());

            if (t == null) {
                t = new Thread(this, "Client");
                t.start();
            }

        } catch (Exception ex) {
            System.out.println("Error di constructor client: " + ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu5 = new javax.swing.JMenu();
        lblName = new javax.swing.JLabel();
        menuNavBar = new javax.swing.JMenuBar();
        menuReservation = new javax.swing.JMenu();
        menuReservationHistory = new javax.swing.JMenu();
        menuNewReservation = new javax.swing.JMenu();
        menuProfil = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setText("       ");

        menuReservation.setText("Reservation");
        menuReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuReservationHistory.setText("Reservation History");
        menuReservationHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuReservationHistory);

        menuNewReservation.setText("New Reservation");
        menuNewReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuNewReservation);

        menuNavBar.add(menuReservation);

        menuProfil.setText("Profil");
        menuProfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuNavBar.add(menuProfil);

        menuLogOut.setText("Logout");
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuNavBar.add(menuLogOut);

        setJMenuBar(menuNavBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblName)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblName)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account a = new Account();
                new FormDashboardCustomer(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenuBar menuNavBar;
    private javax.swing.JMenu menuNewReservation;
    private javax.swing.JMenu menuProfil;
    private javax.swing.JMenu menuReservation;
    private javax.swing.JMenu menuReservationHistory;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        sendMessage(user.getUsername() + ";LOGIN");
        while (true) {
            try {
                getMessage();
            } catch (Exception ex) {
                System.out.println("Error di client : " + ex);
            }
        }
    }
    
    private void getMessage() throws IOException {
        String chatServer;
        chatServer = in.readLine();
    }

    public void sendMessage(String message) {
        try {
            out.writeBytes(user.getUsername() + ": " + message + "\n");
        } catch (Exception e) {
            System.out.println("Error di send message client");
        }
    }
}
