/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

import com.restaurant.services.*;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas
 */
public class FormDashboardAdmin extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form FormDashboardAdmin
     */
    Account user;
    Socket clientSocket;
    Thread t;
    BufferedReader in;
    DataOutputStream out;
    
    public FormDashboardAdmin(Account a) {
        initComponents();
        user = a;
        try {
            initComponents();
            setLocationRelativeTo(null);
            clientSocket = new Socket("localhost", 6000);
            in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            out = new DataOutputStream(clientSocket.getOutputStream());
            
            lblName.setText("Welcome, admin " + user.getFullname());

            if (t == null) {
                t = new Thread(this, "Admin");
                t.start();
            }
             
        } catch (Exception ex) {
            System.out.println("Error di constructor admin: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuReservation = new javax.swing.JMenu();
        menuReservationManagement = new javax.swing.JMenu();
        menuReservationHistory = new javax.swing.JMenu();
        menuFood = new javax.swing.JMenu();
        menuOrder = new javax.swing.JMenu();
        menuTable = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuReservation.setText("Reservation");
        menuReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuReservationManagement.setText("Reservation Management");
        menuReservationManagement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuReservationManagement);

        menuReservationHistory.setText("Reservation History");
        menuReservationHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuReservationHistory);

        jMenuBar2.add(menuReservation);

        menuFood.setText("Food Menu");
        menuFood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuFood);

        menuOrder.setText("Order");
        menuOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuOrder);

        menuTable.setText("Table");
        menuTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuTable);

        menuLogOut.setText("Logout");
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuLogOut);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblName)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblName)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account a = new Account();
                new FormDashboardAdmin(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenu menuFood;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuReservation;
    private javax.swing.JMenu menuReservationHistory;
    private javax.swing.JMenu menuReservationManagement;
    private javax.swing.JMenu menuTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        sendMessage(user.getUsername() + ";LOGIN");
        while (true) {
            try {
                getMessage();
            } catch (Exception ex) {
                System.out.println("Error di admin : " + ex);
            }
        }
    }
    
    private void getMessage() throws IOException {
        String chatServer;
        chatServer = in.readLine();
    }

    public void sendMessage(String message) {
        try {
            out.writeBytes(user.getUsername() + ": " + message + "\n");
        } catch (Exception e) {
            System.out.println("Error di send message admin");
        }
    }
}
