/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

/**
 *
 * @author Nicholas
 */
public class FormDashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboardAdmin
     */
    public FormDashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuReservation = new javax.swing.JMenu();
        menuReservationManagement = new javax.swing.JMenu();
        menuReservationHistory = new javax.swing.JMenu();
        menuFood = new javax.swing.JMenu();
        menuOrder = new javax.swing.JMenu();
        menuTable = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelName.setText("Welcome, XXXXXXX");

        menuReservation.setText("Reservation");
        menuReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuReservationManagement.setText("Reservation Management");
        menuReservationManagement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuReservationManagement);

        menuReservationHistory.setText("Reservation History");
        menuReservationHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuReservation.add(menuReservationHistory);

        jMenuBar2.add(menuReservation);

        menuFood.setText("Food Menu");
        menuFood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuFood);

        menuOrder.setText("Order");
        menuOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuOrder);

        menuTable.setText("Table");
        menuTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuTable);

        menuLogOut.setText("Logout");
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.add(menuLogOut);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelName)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelName)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel labelName;
    private javax.swing.JMenu menuFood;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuReservation;
    private javax.swing.JMenu menuReservationHistory;
    private javax.swing.JMenu menuReservationManagement;
    private javax.swing.JMenu menuTable;
    // End of variables declaration//GEN-END:variables
}
