/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurant_tidakpakaidollar.*;

/**
 *
 * @author Nicholas
 */
public class FormDashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboardAdmin
     */
    int currentUserId;
    String currentUsername;
    Restaurant_tidakpakaidollar restaurantClient;
    public FormDashboardAdmin() {
        initComponents();
    }
    public FormDashboardAdmin(Restaurant_tidakpakaidollar parent, int userId, String username) 
    {
        initComponents();
        this.restaurantClient = parent;
        this.currentUserId = userId;
        this.currentUsername = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuReservation = new javax.swing.JMenu();
        menuItemReservationMan = new javax.swing.JMenuItem();
        menuItemReservationHis = new javax.swing.JMenuItem();
        menuFood = new javax.swing.JMenu();
        menuItemFoodMenu = new javax.swing.JMenuItem();
        menuOrder = new javax.swing.JMenu();
        menuItemOrder = new javax.swing.JMenuItem();
        menuTable = new javax.swing.JMenu();
        menuItemTable = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuReservation.setText("Reservation");
        menuReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemReservationMan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemReservationMan.setText("Reservation Management");
        menuItemReservationMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservationManActionPerformed(evt);
            }
        });
        menuReservation.add(menuItemReservationMan);

        menuItemReservationHis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemReservationHis.setText("Reservation History");
        menuItemReservationHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservationHisActionPerformed(evt);
            }
        });
        menuReservation.add(menuItemReservationHis);

        jMenuBar2.add(menuReservation);

        menuFood.setText("Food Menu");
        menuFood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemFoodMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemFoodMenu.setText("Menu");
        menuItemFoodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFoodMenuActionPerformed(evt);
            }
        });
        menuFood.add(menuItemFoodMenu);

        jMenuBar2.add(menuFood);

        menuOrder.setText("Order");
        menuOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemOrder.setText("Order");
        menuItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrderActionPerformed(evt);
            }
        });
        menuOrder.add(menuItemOrder);

        jMenuBar2.add(menuOrder);

        menuTable.setText("Table");
        menuTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemTable.setText("Table");
        menuItemTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTableActionPerformed(evt);
            }
        });
        menuTable.add(menuItemTable);

        jMenuBar2.add(menuTable);

        menuLogOut.setText("Logout");
        menuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuLogOut.add(menuItemLogout);

        jMenuBar2.add(menuLogOut);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblName)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblName)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemReservationHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservationHisActionPerformed
        // TODO add your handling code here:
        FormReservationHistory resHis = new FormReservationHistory(this);
        resHis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemReservationHisActionPerformed

    private void menuItemReservationManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservationManActionPerformed
        // TODO add your handling code here:
        FormReservationManagement resMan = null;
        try {
            resMan = new FormReservationManagement(this);
        } catch (IOException ex) {
            Logger.getLogger(FormDashboardAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        resMan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemReservationManActionPerformed

    private void menuItemFoodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFoodMenuActionPerformed
        // TODO add your handling code here:
        FormMenuManagement menuMan = new FormMenuManagement(this);
        menuMan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemFoodMenuActionPerformed

    private void menuItemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrderActionPerformed
        // TODO add your handling code here:
        FormOrderMonitoring orderMon = new FormOrderMonitoring(this);
        orderMon.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemOrderActionPerformed

    private void menuItemTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTableActionPerformed
        // TODO add your handling code here:
        FormTableManagement tableMan = new FormTableManagement(this);
        tableMan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemTableActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure want to logout?",
                "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                restaurantClient.sendMessageToServer("LOGOUT");
                restaurantClient.stopThread();
                this.dispose();
                Restaurant_tidakpakaidollar newApp = new Restaurant_tidakpakaidollar();
                FormLogin login = new FormLogin(newApp);
                login.setVisible(true);

            } catch (IOException ex) {
                Logger.getLogger(FormDashboardAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenu menuFood;
    private javax.swing.JMenuItem menuItemFoodMenu;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemOrder;
    private javax.swing.JMenuItem menuItemReservationHis;
    private javax.swing.JMenuItem menuItemReservationMan;
    private javax.swing.JMenuItem menuItemTable;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuReservation;
    private javax.swing.JMenu menuTable;
    // End of variables declaration//GEN-END:variables

       
    
}