/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicholas
 */
public class FormMenuManagement extends javax.swing.JFrame {

    FormDashboardAdmin dashboard;
    int menuId = 0;
    /**
     * Creates new form FormMenuManagement
     */
    public FormMenuManagement(FormDashboardAdmin admin) {
        initComponents();
        this.dashboard = admin;
        
        loadData("GET_MENU");
        
        // Initial state for combo box
        if (cmbCari.getSelectedIndex() == 0) {
            cmbKategori.setEnabled(true);
            txtCariMenu.setEnabled(false);
        } else {
            cmbKategori.setEnabled(false);
            txtCariMenu.setEnabled(true);
        }
    }
    
    public void loadData(String request) {
        try {
            dashboard.restaurantClient.sendMessageToServer(request);
            String response = dashboard.restaurantClient.getMessageFromServer();
            
            DefaultTableModel model = (DefaultTableModel) tableMenuManagement.getModel();
            model.setRowCount(0);
            
            if (response == null || response.isEmpty()) return;
            
            String[] menus = response.split("#");
            for (String menuStr : menus) {
                if (menuStr.trim().isEmpty()) continue;
                String[] details = menuStr.split(";");
                if (details.length >= 5) {
                    model.addRow(new Object[]{
                        Integer.parseInt(details[0]),
                        details[1],
                        details[2],
                        Integer.parseInt(details[3]),
                        Integer.parseInt(details[4])
                    });
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(FormMenuManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        lblMenuManagement = new javax.swing.JLabel();
        jScrollPaneMenuManagement = new javax.swing.JScrollPane();
        tableMenuManagement = new javax.swing.JTable();
        lblNewMenu = new javax.swing.JLabel();
        btnNewMenu = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        lblCariBerdasarkan = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();
        lblCari = new javax.swing.JLabel();
        txtCariMenu = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        btnTambahStok = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbllCurrentMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblMenuManagement.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMenuManagement.setText("Menu Management");

        tableMenuManagement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableMenuManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Category", "Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMenuManagement.setRowHeight(30);
        tableMenuManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMenuManagementMouseClicked(evt);
            }
        });
        jScrollPaneMenuManagement.setViewportView(tableMenuManagement);

        lblNewMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNewMenu.setText("Add New Menu");

        btnNewMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNewMenu.setText("+");
        btnNewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMenuActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        lblCariBerdasarkan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCariBerdasarkan.setText("Cari Berdasarkan");

        cmbCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Nama" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });

        lblCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCari.setText("Cari");

        txtCariMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCariMenu.setEnabled(false);

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));

        btnTambahStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTambahStok.setText("Tambah Stok");
        btnTambahStok.setActionCommand("");
        btnTambahStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahStokActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setActionCommand("");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setActionCommand("");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbllCurrentMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbllCurrentMenu.setText("ID Menu: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addContainerGap(722, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneMenuManagement)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCari)
                                        .addGap(28, 28, 28)
                                        .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCariMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCariBerdasarkan)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCari)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnTambahStok))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbllCurrentMenu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNewMenu)))))
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuManagement)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMenuManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariBerdasarkan)
                    .addComponent(lblNewMenu)
                    .addComponent(btnNewMenu)
                    .addComponent(lbllCurrentMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCariMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahStok)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMenuManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMenuActionPerformed
        // TODO add your handling code here:
        FormTambahMenu tambahMenu = new FormTambahMenu(this);
        tambahMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewMenuActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String filterBy = "", value = "";
        String request = "";
        if (cmbCari.getSelectedIndex() == 0) {
            filterBy = "category";
            value = cmbKategori.getSelectedItem().toString();
            if (value.equals("Makanan")) {
                value = "FOOD";
            } else {
                value = "DRINK";
            }
        } else if (cmbCari.getSelectedIndex() == 1) {
            filterBy = "name";
            value = txtCariMenu.getText().trim();
        }

        if (value.isEmpty()) {
            request = "GET_MENU";
        } else {
            request = "GET_MENU;" + filterBy + ";" + value;
        }
        
        loadData(request);
    }//GEN-LAST:event_btnCariActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        if (cmbCari.getSelectedIndex() == 0) {
            cmbKategori.setEnabled(true);
            txtCariMenu.setEnabled(false);
        } else if (cmbCari.getSelectedIndex() == 1) {
            cmbKategori.setEnabled(false);
            txtCariMenu.setEnabled(true);
        }
    }//GEN-LAST:event_cmbCariActionPerformed

    private void btnTambahStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahStokActionPerformed
        int selectedRow = tableMenuManagement.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih menu dari tabel terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int menuId = Integer.parseInt(tableMenuManagement.getValueAt(selectedRow, 0).toString());
            String menuName = tableMenuManagement.getValueAt(selectedRow, 1).toString();

            String input = javax.swing.JOptionPane.showInputDialog(this, "Berapa banyak stok yang ingin ditambahkan untuk menu " + menuName + "?", "Tambah Stok", javax.swing.JOptionPane.QUESTION_MESSAGE);
            
            if (input == null || input.trim().isEmpty()) {
                return;
            }

            int addedStock = Integer.parseInt(input.trim());
            if (addedStock <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Jumlah stok harus lebih dari 0!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            String request = "ADD_STOCK;" + menuId + ";" + addedStock;
            dashboard.restaurantClient.sendMessageToServer(request);
            String response = dashboard.restaurantClient.getMessageFromServer();

            if ("SUCCESS".equals(response)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Stok berhasil ditambahkan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                loadData("GET_MENU");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan stok!" + response, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input stok harus berupa angka!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormMenuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahStokActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (menuId == 0)
        {
            JOptionPane.showMessageDialog(this, "Pilih menu terlebih dahulu");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, "Hapus menu id: " + menuId, "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String request = "DELETE_MENU;" + menuId;
            try {
                dashboard.restaurantClient.sendMessageToServer(request);
                dashboard.restaurantClient.response = dashboard.restaurantClient.getMessageFromServer();
                String response = dashboard.restaurantClient.response;
                if (response.equals("SUCCESS"))
                {
                    JOptionPane.showMessageDialog(this, "Sukses hapus menu id: " + menuId);
                }            
                loadData("GET_MENU");
            } catch (IOException ex) {
                Logger.getLogger(FormOrderMonitoring.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (menuId == 0) {
            JOptionPane.showMessageDialog(this, "Pilih menu terlebih dahulu");
            return;
        }
        try {
            // TODO add your handling code here:
            FormEditMenu m = new FormEditMenu(this, menuId);
            m.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(FormMenuManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tableMenuManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuManagementMouseClicked
        // TODO add your handling code here:
        
        int row = tableMenuManagement.getSelectedRow();
        if (row >= 0) {
            menuId = Integer.parseInt(tableMenuManagement.getValueAt(row, 0).toString());
            lbllCurrentMenu.setText("Menu Id: " + menuId);
        }
    }//GEN-LAST:event_tableMenuManagementMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuManagement(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewMenu;
    private javax.swing.JButton btnTambahStok;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JScrollPane jScrollPaneMenuManagement;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblCariBerdasarkan;
    private javax.swing.JLabel lblMenuManagement;
    private javax.swing.JLabel lblNewMenu;
    private javax.swing.JLabel lbllCurrentMenu;
    private javax.swing.JTable tableMenuManagement;
    private javax.swing.JTextField txtCariMenu;
    // End of variables declaration//GEN-END:variables
}