/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicholas
 */
public class FormTableManagement extends javax.swing.JFrame {

    private FormDashboardAdmin dashboard;
    String[][] allTable;
    String[][] allTableRes;
    /**
     * Creates new form FormTableManagement
     */
    public FormTableManagement(FormDashboardAdmin admin) throws IOException {
        initComponents();
        this.dashboard = admin;
        
        String request = "GET_TABLE";
        dashboard.restaurantClient.sendMessageToServer(request);
        
        String tables = dashboard.restaurantClient.getMessageFromServer();
        
        String[] table_data = tables.split("#");
        allTable = new String[table_data.length][4];
        
        for(int i=0; i<table_data.length; i++){
            String tableDetail[]=table_data[i].split(";");
            for(int j=0; j<4; j++){
                allTable[i][j] = tableDetail[j];
            }
        }
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTableManagement = new javax.swing.JScrollPane();
        tableTableManagement = new javax.swing.JTable();
        lblTableManagement = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        lblTableNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTableReservationInfo = new javax.swing.JTable();
        lblTableManagement2 = new javax.swing.JLabel();
        lblTableManagement3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableTableManagement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableTableManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Number", "Capacity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTableManagement.setRowHeight(30);
        tableTableManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTableManagementMouseClicked(evt);
            }
        });
        jScrollPaneTableManagement.setViewportView(tableTableManagement);

        lblTableManagement.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTableManagement.setText("Table Management");

        buttonExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        lblTableNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableNum.setText("0");

        tableTableReservationInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableTableReservationInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Date", "Status", "Name", "Guest"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTableReservationInfo.setRowHeight(30);
        jScrollPane1.setViewportView(tableTableReservationInfo);

        lblTableManagement2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableManagement2.setText("Table Reservation Information");

        lblTableManagement3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableManagement3.setText("Table Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(buttonExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(lblTableManagement)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 554, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTableManagement3)
                                .addGap(18, 18, 18)
                                .addComponent(lblTableNum))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTableManagement2)
                        .addGap(157, 157, 157))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPaneTableManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(580, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTableManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lblTableManagement2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTableManagement3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTableNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonExit)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jScrollPaneTableManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) tableTableManagement.getModel();
        model.setRowCount(0);
        
        Object[] rowData = new Object[4];
        
        for(int i=0; i<allTable.length; i++){
            for(int j=0; j<4; j++){
                rowData[j] = allTable[i][j];
            }
            model.addRow(rowData);
        }
    }
    public void refreshTableReserved(){
        DefaultTableModel model = (DefaultTableModel) tableTableReservationInfo.getModel();
        model.setRowCount(0);
        
        Object[] rowData = new Object[5];
        
        for(int i=0; i<allTableRes.length; i++){
            for(int j=0; j<5; j++){
                rowData[j] = allTableRes[i][j];
            }
            model.addRow(rowData);
        }
    }
    
    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void tableTableManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTableManagementMouseClicked
        // TODO add your handling code here:
        try {
            int row = tableTableManagement.getSelectedRow();
            if (row >= 0) {
                int id_table = Integer.parseInt(tableTableManagement.getValueAt(row, 0).toString());
                lblTableNum.setText(id_table + "");

                String request = "GET_TABLE_RESERVED;" + id_table;
                dashboard.restaurantClient.sendMessageToServer(request);

                String table_res = dashboard.restaurantClient.getMessageFromServer();
                
                String[] tableRes_data = table_res.split("#");
                allTableRes = new String[tableRes_data.length][5];

                for (int i = 0; i < tableRes_data.length; i++) {
                    String tableResDetail[] = tableRes_data[i].split(";");
                    for (int j = 0; j < 5; j++) {
                        allTableRes[i][j] = tableResDetail[j];
                    }
                }
                refreshTableReserved();
            }
           
        } catch(IOException ex){
            Logger.getLogger(FormTableManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableTableManagementMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormTableManagement(null).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FormTableManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTableManagement;
    private javax.swing.JLabel lblTableManagement;
    private javax.swing.JLabel lblTableManagement2;
    private javax.swing.JLabel lblTableManagement3;
    private javax.swing.JLabel lblTableNum;
    private javax.swing.JTable tableTableManagement;
    private javax.swing.JTable tableTableReservationInfo;
    // End of variables declaration//GEN-END:variables
}