/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_tidakpakedollar;

/**
 *
 * @author Nicholas
 */
public class FormReservationHistory extends javax.swing.JFrame {

    FormDashboardAdmin dashboard;
    java.util.ArrayList<Integer> currentReservationIds = new java.util.ArrayList<>();
    /**
     * Creates new form FormReservationHistory
     */
    public FormReservationHistory(FormDashboardAdmin admin) {
        initComponents();
        this.dashboard = admin;
        
        cmbFilter.removeAllItems();
        cmbFilter.addItem("Semua Periode");
        cmbFilter.addItem("1 Minggu Terakhir");
        cmbFilter.addItem("1 Bulan Terakhir");
        cmbFilter.addItem("1 Tahun Terakhir");
        
        loadData("Semua Periode");
    }

    public void loadData(String filter) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableUpcomingReservation.getModel();
        model.setRowCount(0);
        currentReservationIds.clear();
        
        try {
            dashboard.restaurantClient.sendMessageToServer("GET_RESERVATION");
            String response = dashboard.restaurantClient.getMessageFromServer();
            
            if (response != null && !response.isEmpty() && !response.equals("ERROR")) {
                String[] reservations = response.split("#");
                java.time.LocalDateTime now = java.time.LocalDateTime.now();
                java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                
                for (String res : reservations) {
                    if (res.trim().isEmpty()) continue;
                    
                    String[] data = res.split(";");
                    if (data.length < 5) continue;
                    
                    String datetimeStr = data[1];
                    if (datetimeStr.length() > 19) {
                        datetimeStr = datetimeStr.substring(0, 19);
                    }
                    
                    java.time.LocalDateTime resDate = null;
                    try {
                        resDate = java.time.LocalDateTime.parse(datetimeStr, formatter);
                    } catch (Exception e) {
                        System.out.println("Parse error: " + e.getMessage());
                    }
                    
                    boolean include = true;
                    if (resDate != null && !filter.equals("Semua Periode")) {
                        if (filter.equals("1 Minggu Terakhir")) {
                            if (resDate.isBefore(now.minusWeeks(1))) include = false;
                        } else if (filter.equals("1 Bulan Terakhir")) {
                            if (resDate.isBefore(now.minusMonths(1))) include = false;
                        } else if (filter.equals("1 Tahun Terakhir")) {
                            if (resDate.isBefore(now.minusYears(1))) include = false;
                        }
                    }
                    
                    if (include) {
                        String date = datetimeStr.split(" ")[0];
                        String time = datetimeStr.split(" ")[1];
                        model.addRow(new Object[]{date, time, data[2], data[3], data[4]});
                        currentReservationIds.add(Integer.parseInt(data[0]));
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println("Error loading reservation data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneReservationHistory = new javax.swing.JScrollPane();
        tableUpcomingReservation = new javax.swing.JTable();
        lblFilter = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        cmbFilter = new javax.swing.JComboBox<>();
        lblReservationHistory = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableUpcomingReservation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableUpcomingReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Status", "Guest", "Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneReservationHistory.setViewportView(tableUpcomingReservation);

        lblFilter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilter.setText("Filter:");

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Periode", "1 Minggu Terakhir", "1 Bulan Terakhir", "1 Tahun Terakhir" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });

        lblReservationHistory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblReservationHistory.setText("Reservation History");

        btnDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDetails.setText("Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReservationHistory)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetails)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExit)
                        .addComponent(jScrollPaneReservationHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblReservationHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPaneReservationHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        if (cmbFilter.getSelectedItem() != null) {
            loadData(cmbFilter.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selectedRow = tableUpcomingReservation.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih reservasi dari tabel terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int resId = currentReservationIds.get(selectedRow);
        try {
            dashboard.restaurantClient.sendMessageToServer("GET_ORDER_DETAILS;" + resId);
            String response = dashboard.restaurantClient.getMessageFromServer();
            
            if (response == null || response.trim().isEmpty() || response.equals("ERROR")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada pesanan untuk reservasi ini.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            String[] items = response.split("#");
            StringBuilder sb = new StringBuilder();
            sb.append("Detail Pesanan:\n\n");
            int grandTotal = 0;
            for (String item : items) {
                if (item.trim().isEmpty()) continue;
                String[] parts = item.split(";");
                if (parts.length < 3) continue;
                String menuName = parts[0];
                int amount = Integer.parseInt(parts[1]);
                int subtotal = Integer.parseInt(parts[2]);
                
                sb.append("- ").append(menuName).append(" x").append(amount)
                  .append(" = Rp ").append(subtotal).append("\n");
                grandTotal += subtotal;
            }
            sb.append("\nGrand Total: Rp ").append(grandTotal);
            
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Detail Pesanan", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat detail pesanan! " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservationHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservationHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservationHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservationHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservationHistory(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JScrollPane jScrollPaneReservationHistory;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblReservationHistory;
    private javax.swing.JTable tableUpcomingReservation;
    // End of variables declaration//GEN-END:variables
}